# Cloudflare Pages configuration for React Portfolio
name = "portfolio-site"
compatibility_date = "2024-01-01"

# Pages configuration
[env.production]
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare Dashboard)
# GMAIL_USER = "your-gmail@gmail.com"
# GMAIL_APP_PASSWORD = "your-app-password"
# RECIPIENT_EMAIL = "saddathasan94@gmail.com"
# SMTP_HOST = "smtp.gmail.com"
# SMTP_PORT = "587"
# SMTP_SECURE = "false"
# RATE_LIMIT_MAX = "5"
# EMAILJS_SERVICE_ID = "your-service-id"
# EMAILJS_TEMPLATE_ID = "your-template-id"
# EMAILJS_USER_ID = "your-user-id"
# GMAIL_ACCESS_TOKEN = "your-access-token"

# Build configuration
[build]
command = "npm run build"
publish = "dist"

# Pages build output directory
pages_build_output_dir = "dist"

# Functions configuration
[functions]
directory = "functions"

# Development configuration
[dev]
port = 8788
local_protocol = "http"