/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GitProfileRouteImport } from './routes/git-profile'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as IbExtensionPrivacyPolicyRouteImport } from './routes/ib-extension/privacy-policy'
import { Route as BlogCategoryIndexRouteImport } from './routes/blog.$category.index'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.$category.$slug'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GitProfileRoute = GitProfileRouteImport.update({
  id: '/git-profile',
  path: '/git-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const IbExtensionPrivacyPolicyRoute =
  IbExtensionPrivacyPolicyRouteImport.update({
    id: '/ib-extension/privacy-policy',
    path: '/ib-extension/privacy-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCategoryIndexRoute = BlogCategoryIndexRouteImport.update({
  id: '/blog/$category/',
  path: '/blog/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/$category/$slug',
  path: '/blog/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/git-profile': typeof GitProfileRoute
  '/home': typeof HomeRoute
  '/projects': typeof ProjectsRoute
  '/ib-extension/privacy-policy': typeof IbExtensionPrivacyPolicyRoute
  '/blog': typeof BlogIndexRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/blog/$category': typeof BlogCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/git-profile': typeof GitProfileRoute
  '/home': typeof HomeRoute
  '/projects': typeof ProjectsRoute
  '/ib-extension/privacy-policy': typeof IbExtensionPrivacyPolicyRoute
  '/blog': typeof BlogIndexRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/blog/$category': typeof BlogCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/git-profile': typeof GitProfileRoute
  '/home': typeof HomeRoute
  '/projects': typeof ProjectsRoute
  '/ib-extension/privacy-policy': typeof IbExtensionPrivacyPolicyRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/git-profile'
    | '/home'
    | '/projects'
    | '/ib-extension/privacy-policy'
    | '/blog'
    | '/blog/$category/$slug'
    | '/blog/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/git-profile'
    | '/home'
    | '/projects'
    | '/ib-extension/privacy-policy'
    | '/blog'
    | '/blog/$category/$slug'
    | '/blog/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/experience'
    | '/git-profile'
    | '/home'
    | '/projects'
    | '/ib-extension/privacy-policy'
    | '/blog/'
    | '/blog/$category/$slug'
    | '/blog/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  GitProfileRoute: typeof GitProfileRoute
  HomeRoute: typeof HomeRoute
  ProjectsRoute: typeof ProjectsRoute
  IbExtensionPrivacyPolicyRoute: typeof IbExtensionPrivacyPolicyRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogCategoryIndexRoute: typeof BlogCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-profile': {
      id: '/git-profile'
      path: '/git-profile'
      fullPath: '/git-profile'
      preLoaderRoute: typeof GitProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ib-extension/privacy-policy': {
      id: '/ib-extension/privacy-policy'
      path: '/ib-extension/privacy-policy'
      fullPath: '/ib-extension/privacy-policy'
      preLoaderRoute: typeof IbExtensionPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$category/': {
      id: '/blog/$category/'
      path: '/blog/$category'
      fullPath: '/blog/$category'
      preLoaderRoute: typeof BlogCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$category/$slug': {
      id: '/blog/$category/$slug'
      path: '/blog/$category/$slug'
      fullPath: '/blog/$category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  GitProfileRoute: GitProfileRoute,
  HomeRoute: HomeRoute,
  ProjectsRoute: ProjectsRoute,
  IbExtensionPrivacyPolicyRoute: IbExtensionPrivacyPolicyRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogCategoryIndexRoute: BlogCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
